# Generated by Django 5.1.1 on 2024-09-23 12:13

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(max_length=50, verbose_name="nom plateforme"),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="slogan"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="email"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="monnaie"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="contact"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="adresse"
                    ),
                ),
                (
                    "sms_api_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SMS Base URL",
                    ),
                ),
                (
                    "notification_api_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Notification API ID",
                    ),
                ),
                (
                    "notification_api_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Notification API KEY",
                    ),
                ),
                (
                    "notification_api_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Notification Base URL",
                    ),
                ),
                (
                    "sms_api_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="SMS API ID"
                    ),
                ),
                (
                    "sms_api_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="SMS API KEY",
                    ),
                ),
                (
                    "email_api_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email Base URL",
                    ),
                ),
                (
                    "email_api_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email API ID",
                    ),
                ),
                (
                    "email_api_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email API KEY",
                    ),
                ),
                (
                    "transaction_api_url",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Paiement Base URL",
                    ),
                ),
                (
                    "transaction_api_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Paiement API ID",
                    ),
                ),
                (
                    "transaction_api_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Paiement API KEY",
                    ),
                ),
                ("logo", models.ImageField(upload_to="uploaded_media/config/logos")),
                (
                    "logo_symbol",
                    models.ImageField(upload_to="uploaded_media/config/logo_symbols"),
                ),
                (
                    "favicon",
                    models.ImageField(upload_to="uploaded_media/config/favicons"),
                ),
                (
                    "minimum_retrait",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant minimum de retrait",
                    ),
                ),
                (
                    "minimum_depot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant minimum de dépôt",
                    ),
                ),
                (
                    "note_information",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="note d'information"
                    ),
                ),
                (
                    "faq",
                    tinymce.models.HTMLField(blank=True, null=True, verbose_name="faq"),
                ),
                (
                    "about",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="a propos"
                    ),
                ),
                (
                    "privacy_policy",
                    tinymce.models.HTMLField(
                        blank=True,
                        null=True,
                        verbose_name="politique de confidentialité",
                    ),
                ),
                (
                    "condition_term",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Conditions d'utilisation"
                    ),
                ),
                (
                    "delai_tour",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="délai tour (sec)"
                    ),
                ),
                (
                    "etat_retrait",
                    models.BooleanField(default=True, verbose_name="état retrait"),
                ),
                (
                    "etat_validation_prealable_retrait",
                    models.BooleanField(
                        default=True, verbose_name="état validation prealable retrait"
                    ),
                ),
                (
                    "etat_depot",
                    models.BooleanField(default=True, verbose_name="état dépôt"),
                ),
                (
                    "etat_partie",
                    models.BooleanField(default=True, verbose_name="état partie"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_configs",
                        related_query_name="modifie_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "config",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Mise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant",
                    ),
                ),
                (
                    "nombre_minimum",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="nombre minimum participants",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="observation"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_mises",
                        related_query_name="modifie_mise",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "mise",
                "ordering": ["montant", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="TauxCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="taux",
                    ),
                ),
                ("debut", models.DateTimeField(verbose_name="date début")),
                (
                    "fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date fin"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="observation"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_taux_commissions",
                        related_query_name="modifie_taux_commission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "taux commission",
                "ordering": ["-debut"],
            },
        ),
        migrations.CreateModel(
            name="TauxTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dépôt", "Depot"),
                            ("Retrait", "Retrait"),
                            ("Mise", "Mise"),
                            ("Gain", "Gain"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="type transaction",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="taux",
                    ),
                ),
                ("debut", models.DateTimeField(verbose_name="date début")),
                (
                    "fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date fin"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="observation"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_taux_transactions",
                        related_query_name="modifie_taux_transaction",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "taux transaction",
                "ordering": ["-debut"],
            },
        ),
    ]
