# Generated by Django 4.2.16 on 2024-10-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mise',
            options={'ordering': ['-montant', '-date_creation'], 'verbose_name': 'mise'},
        ),
    ]
