# Generated by Django 4.2.16 on 2024-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_mise_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="transaction_api_password",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Paiement API PASSWORD",
            ),
        ),
    ]
