# Generated by Django 5.1.1 on 2024-09-23 14:42

import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_facebook",
                    models.CharField(editable=False, max_length=25, unique=True),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="nom"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="prénom(s)"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("Masculin", "Masculin"), ("Féminin", "Feminin")],
                        max_length=20,
                        null=True,
                        verbose_name="genre",
                    ),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="numéro principal",
                    ),
                ),
                (
                    "contact_retrait",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="numéro retrait",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploaded_media/photo_player",
                        verbose_name="photo",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=25, unique=True)),
                (
                    "code_invite_par",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "invite_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_profils",
                        related_query_name="invitation_profil",
                        to="player.profil",
                        verbose_name="invité par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_profils",
                        related_query_name="modifie_profil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifié par",
                    ),
                ),
                (
                    "pays_residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pays_profils",
                        related_query_name="pays_profil",
                        to="cities_light.country",
                        verbose_name="pays",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_profil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Partie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=25, unique=True)),
                (
                    "nombre_participants",
                    models.PositiveIntegerField(verbose_name="nombre participants"),
                ),
                (
                    "montant_mise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant mise",
                    ),
                ),
                (
                    "montant_cagnotte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant cagnotte",
                    ),
                ),
                (
                    "montant_commission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant commission",
                    ),
                ),
                (
                    "visibilite",
                    models.CharField(
                        blank=True,
                        choices=[("Public", "Public"), ("Privée", "Privee")],
                        default="Public",
                        max_length=20,
                        null=True,
                        verbose_name="visibilité",
                    ),
                ),
                (
                    "delai_tour",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="délai tour par joueur (sec)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "date_demarrage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date démarrage"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date fin"
                    ),
                ),
                (
                    "etat_demarrage",
                    models.BooleanField(default=False, verbose_name="état démarrage"),
                ),
                (
                    "etat_fin",
                    models.BooleanField(default=False, verbose_name="état fin"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_parties",
                        related_query_name="config_partie",
                        to="core.config",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "mise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mise_parties",
                        related_query_name="mise_partie",
                        to="core.mise",
                        verbose_name="mise",
                    ),
                ),
                (
                    "taux_comission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taux_comission_parties",
                        related_query_name="taux_comission_partie",
                        to="core.tauxcommission",
                        verbose_name="taux de comission",
                    ),
                ),
                (
                    "organise_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organise_par_parties",
                        related_query_name="organise_par_partie",
                        to="player.profil",
                        verbose_name="organisé par",
                    ),
                ),
                (
                    "vainqueur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vainqueur_parties",
                        related_query_name="vainqueur_partie",
                        to="player.profil",
                        verbose_name="vainqueur",
                    ),
                ),
            ],
            options={
                "verbose_name": "partie",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "date_demarrage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date démarrage"
                    ),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date fin"
                    ),
                ),
                (
                    "etat_demarrage",
                    models.BooleanField(default=False, verbose_name="état démarrage"),
                ),
                (
                    "etat_fin",
                    models.BooleanField(default=False, verbose_name="état fin"),
                ),
                (
                    "etat_exclusion",
                    models.BooleanField(default=False, verbose_name="état exclusion"),
                ),
                (
                    "etat_victoire",
                    models.BooleanField(default=False, verbose_name="état victoire"),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partie_participations",
                        related_query_name="partie_participation",
                        to="player.partie",
                        verbose_name="partie",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_participations",
                        related_query_name="profil_participation",
                        to="player.profil",
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objet",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="objet"
                    ),
                ),
                (
                    "message",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="message"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_historique_notifications",
                        related_query_name="profil_historique_notification",
                        to="player.profil",
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique notification",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=25, unique=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dépôt", "Depot"),
                            ("Retrait", "Retrait"),
                            ("Mise", "Mise"),
                            ("Gain", "Gain"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="type transaction",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant",
                    ),
                ),
                (
                    "frais_genere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="frais généré",
                    ),
                ),
                (
                    "depot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant dépôt",
                    ),
                ),
                (
                    "retrait",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant retrait",
                    ),
                ),
                (
                    "mise",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant mise",
                    ),
                ),
                (
                    "gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="montant gain",
                    ),
                ),
                (
                    "description",
                    models.CharField(editable=False, max_length=225, unique=True),
                ),
                (
                    "contact_transaction",
                    models.CharField(
                        editable=False,
                        max_length=225,
                        unique=True,
                        verbose_name="contact transaction",
                    ),
                ),
                (
                    "operateur",
                    models.CharField(
                        editable=False,
                        max_length=225,
                        unique=True,
                        verbose_name="opérateur",
                    ),
                ),
                (
                    "type_api",
                    models.CharField(
                        editable=False,
                        max_length=225,
                        unique=True,
                        verbose_name="type API",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_transactions",
                        related_query_name="config_transaction",
                        to="core.config",
                        verbose_name="configuration",
                    ),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partie_transactions",
                        related_query_name="partie_transaction",
                        to="player.partie",
                        verbose_name="partie",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_transactions",
                        related_query_name="profil_transaction",
                        to="player.profil",
                        verbose_name="profil",
                    ),
                ),
                (
                    "taux_frais_genere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taux_frais_transactions",
                        related_query_name="taux_frais_transaction",
                        to="core.tauxtransaction",
                        verbose_name="taux de frais",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valide_transactions",
                        related_query_name="valide_transaction",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="validée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="observation"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="date modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date validation"
                    ),
                ),
                (
                    "date_suppression",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date suppression"
                    ),
                ),
                (
                    "etat_validation",
                    models.BooleanField(default=True, verbose_name="état validation"),
                ),
                (
                    "etat_suppression",
                    models.BooleanField(default=False, verbose_name="état suppression"),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modifie_observations",
                        related_query_name="modifie_observation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modifiée par",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participation_observations",
                        related_query_name="participation_observation",
                        to="player.participation",
                        verbose_name="participation",
                    ),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partie_observations",
                        related_query_name="partie_observation",
                        to="player.partie",
                        verbose_name="partie",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profil_observations",
                        related_query_name="profil_observation",
                        to="player.profil",
                        verbose_name="profil",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_observations",
                        related_query_name="transaction_observation",
                        to="player.transaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "observation",
                "ordering": ["-date_creation"],
            },
        ),
    ]
