# Generated by Django 5.1.1 on 2024-09-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='pays_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays_profils', related_query_name='pays_profil', to='cities_light.country', verbose_name='pays'),
        ),
    ]
