# Generated by Django 4.2.16 on 2024-10-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_profil_pays_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact_transaction',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='contact transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operateur',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='opérateur'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_api',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='type API'),
        ),
    ]
