# Generated by Django 4.2.16 on 2024-10-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_transaction_contact_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='etat_actif',
            field=models.BooleanField(default=True, verbose_name='état actif'),
        ),
    ]
