# Generated by Django 4.2.16 on 2024-10-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_transaction_etat_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='etat_actif',
        ),
    ]
