# Generated by Django 4.2.16 on 2024-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_remove_transaction_etat_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquenotification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date lecture'),
        ),
        migrations.AddField(
            model_name='historiquenotification',
            name='etat_lecture',
            field=models.BooleanField(default=False, verbose_name='état lecture'),
        ),
        migrations.AddField(
            model_name='historiquenotification',
            name='id_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID référence'),
        ),
        migrations.AddField(
            model_name='historiquenotification',
            name='type_reference',
            field=models.CharField(blank=True, choices=[('Profil', 'Profil'), ('Transaction', 'Transaction'), ('Participation', 'Participation'), ('Partie', 'Partie')], max_length=20, null=True, verbose_name='type référence'),
        ),
    ]
