# Generated by Django 4.2.16 on 2024-10-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_historiquenotification_date_lecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiteur_id', models.CharField(max_length=255, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('date_modification', models.DateTimeField(auto_now=True, null=True, verbose_name='date modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='date validation')),
                ('date_suppression', models.DateTimeField(blank=True, null=True, verbose_name='date suppression')),
                ('etat_validation', models.BooleanField(default=True, verbose_name='état validation')),
                ('etat_suppression', models.BooleanField(default=False, verbose_name='état suppression')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_visiteurs', related_query_name='profil_visiteur', to='player.profil', verbose_name='profil')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'ordering': ['-date_creation'],
            },
        ),
    ]
