# Generated by Django 4.2.16 on 2024-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0007_visiteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visiteur",
            name="visiteur_id",
            field=models.CharField(max_length=255),
        ),
    ]
