# Generated by Django 4.2.16 on 2024-10-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_alter_profil_pays_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='code_invite_par',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Invité par (Code)'),
        ),
    ]
